export const datalist = [
  {
    key: 1,
    index: 1,
    label: "商号",
    data: "有限会社 石和工業（いさわこうぎょう）",
    mergedList: [],
    separatedList: [],
    definitionList: [],
  },
  {
    key: 2,
    index: 2,
    label: "本社",
    data: "〒240-0045 神奈川県横浜市保土ヶ谷区川島町 648",
    mergedList: [],
    separatedList: [],
    definitionList: [],
  },
  {
    key: 3,
    index: 3,
    label: "工事部事務所",
    data: "〒240-0045 神奈川県横浜市保土ヶ谷区川島町 648-4-205",
    mergedList: [],
    separatedList: [],
    definitionList: [],
  },
  {
    key: 4,
    index: 4,
    label: "資材置場",
    data: "〒241-0014 神奈川県横浜市旭区市沢町 380",
    mergedList: [],
    separatedList: [],
    definitionList: [],
  },
  {
    key: 5,
    index: 5,
    label: "代表者",
    data: "大林 寿寛",
    mergedList: [],
    separatedList: [],
    definitionList: [],
  },
  {
    key: 6,
    index: 6,
    label: "資本金",
    data: "3,000,000 円",
    mergedList: [],
    separatedList: [],
    definitionList: [],
  },
  {
    key: 7,
    index: 7,
    label: "取引銀行",
    data: "",
    mergedList: ["みずほ銀行（鶴ヶ峰支店）", "横浜信用金庫（西谷支店）"],
    separatedList: [],
    definitionList: [],
  },
  // {
  //   key: 8,
  //   index: 8,
  //   label: "年商（期近決算）",
  //   data: "400,000,000 円",
  //   mergedList: [],
  //   separatedList: [],
  //   definitionList: [],
  // },
  {
    key: 9,
    index: 9,
    label: "社員・職人",
    data: "25 名",
    mergedList: [],
    separatedList: [],
    definitionList: [],
  },
  {
    key: 10,
    index: 10,
    label: "資格等",
    data: "",
    mergedList: [],
    separatedList: [],
    definitionList: [
      {
        index: 1,
        dt: "安全衛生責任者教育",
        dd: "22 名",
      },
      {
        index: 2,
        dt: "ガス溶接",
        dd: "15 名",
      },
      {
        index: 3,
        dt: "高所作業",
        dd: "20 名",
      },
      {
        index: 4,
        dt: "研削砥石",
        dd: "25 名",
      },
      {
        index: 5,
        dt: "車両系",
        dd: "8 名",
      },
      {
        index: 6,
        dt: "その他",
        dd: "粉塵・クレーン・酸欠 等",
      },
    ],
  },
  {
    key: 11,
    index: 11,
    label: "建設業許可",
    data: "神奈川県知事（般-３）第 71831 号",
    mergedList: [],
    separatedList: [
      "とび・土工工事業",
      "土木工事業",
      "舗装工事業",
      "解体工事業",
    ],
    definitionList: [],
  },
  {
    key: 12,
    index: 12,
    label: "産業廃棄物許可",
    data: "神奈川県・東京都 第 1402104032 号",
    mergedList: [],
    separatedList: [],
    definitionList: [],
  },
  {
    key: 13,
    index: 13,
    label: "取引先",
    data: "",
    mergedList: [
      "大成建設株式会社",
      "清水建設株式会社",
      "鹿島建設株式会社",
      "株式会社竹中工務店",
      "南海辰村建設株式会社",
      "大東建託株式会社",
      "日本道路株式会社",
      "佐藤工業株式会社",
      "住協建設株式会社",
      "株式会社NIPPO",
      "風越建設株式会社",
      "その他解体業者",
      "改修工事専門業者",
      "不動産業者",
      "不定期個人 等",
    ],
    separatedList: [],
    definitionList: [],
  },
  {
    key: 14,
    index: 14,
    label: "取引先",
    data: "",
    mergedList: [],
    separatedList: [
      "コンクリート斫工事",
      "コンクリートカッター工事",
      "ダイヤモンドコアボーリング工事",
      "その他コンクリート特殊解体工事",
      "ウォルソー／ワイヤーソー工事",
      "内装解体工事",
      "木造解体工事",
    ],
    definitionList: [],
  },
  {
    key: 15,
    index: 15,
    label: "設備等",
    data: "",
    mergedList: [],
    separatedList: [],
    definitionList: [
      {
        index: 1,
        dt: "３t ダンプ：",
        dd: "２台",
      },
      {
        index: 2,
        dt: "コンプレッサー：",
        dd: "６台",
      },
      {
        index: 3,
        dt: "発電機：",
        dd: "２台",
      },
      {
        index: 4,
        dt: "ハンドブレーカー：",
        dd: "３０台",
      },
      {
        index: 5,
        dt: "9.12 インチカッター：",
        dd: "１０台",
      },
      {
        index: 6,
        dt: "ダイヤモンドコアボーリング工具",
        dd: "",
      },
      {
        index: 7,
        dt: "その他各種解体用工具",
        dd: "",
      },
    ],
  },
];
